---
title: "Referee report. For: Integrated Fire Management and Closer to Nature Forest Management at the Landscape Scale as a Holistic Approach to Foster Forest Resilience to Wildfires [version 3; peer review: 4 approved with reservations, 2 not approved]"
date: "2025-01-01"
description: "This Open Letter by Kalapodis and Sakkas presents a framework for enhancing the resilience of forests against the increasing wildfire issue in Europe by integrating Integrated Fire Management (IFM) and Closer-to-Nature Forest Management…"
categories: ["Peer Review"]
pub-authors: "Donovan, V. M. & **Weidig, N. C.**"
pub-doi: "10.21956/OPENRESEUROPE.21420.R53295"
pub-url: "https://open-research-europe.ec.europa.eu/articles/4-131/v3#referee-response-53295"
pub-listed: "yes"
pub-oa: true
---

::: {.nw-cite-meta}
Donovan, V. M. & **Weidig, N. C.** (2025). 
:::

[DOI](https://doi.org/10.21956/OPENRESEUROPE.21420.R53295){.nw-btn .nw-btn-primary target="_blank"} [BibTeX](cite.bib){.nw-btn .nw-btn-ghost}

## Abstract

This Open Letter by Kalapodis and Sakkas presents a framework for enhancing the resilience of forests against the increasing wildfire issue in Europe by integrating Integrated Fire Management (IFM) and Closer-to-Nature Forest Management (CTNFM). The authors cover a wide array of topics concerning fire suppression, fuel management, wildfire preparedness, and forest resilience. While addressing the recent rise in both the frequency and intensity of wildfires in Europe is relevant, it is unclear whether this paper makes a significant contribution to this effort. A primary concern is that much of the language throughout the letter is unclear and requires numerous changes to improve the flow and readability of the manuscript. Additionally, this manuscript is rather long and winding making it difficult to follow. A key missing piece upon reading the paper is why the authors specifically choose to focus on these two approaches and why do they argue they need to be integrated? It is difficult to assess the validity for the paper since it is unclear what the justification is for the integration of the approaches. Overall, the current version requires substantial revision to clarify their arguments, reduce repetitive language, and improve of the general flow of the manuscript.
